spring:
  application:
    name: usuario-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

mensaje:
  texto: Configuración desde Config Server para Usuario Service

info:
  app:
    nombre: Usuario Service
    descripcion: Microservicio de gestión de usuarios - Help Desk
    version: 1.0.0
    autor: Sheyla Chuco
